In [1]:
from projection import *
import numpy as np

In [2]:
points = np.array([[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0]]) 
ds = ProjectionHandler(points)

In [3]:
query_points = 2 * np.random.rand(10, 3)
print(query_points)

[[0.07728401 0.49343562 1.26067792]
 [1.59312773 1.83861349 0.94325039]
 [1.70811288 1.77663671 1.54733386]
 [0.34615501 1.30916384 1.40885012]
 [0.4009657  0.13866789 1.60938193]
 [1.10622576 1.63879419 0.91030861]
 [0.37221891 0.82096958 0.78561597]
 [1.80818054 0.37420331 0.71004517]
 [1.91216504 0.03100312 0.67967287]
 [0.13027189 0.89257763 1.70158832]]


In [4]:
print(ds.project_points(query_points))

[[-2.49800181e-16  1.16378849e-01  8.83621151e-01]
 [ 3.77257118e-01  6.22742882e-01  4.10782513e-15]
 [ 3.63856466e-01  4.32942248e-01  2.03201286e-01]
 [ 6.66133820e-16  4.50156856e-01  5.49843144e-01]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 2.21116243e-01  7.53684672e-01  2.51990853e-02]
 [ 4.59507577e-02  4.94701425e-01  4.59347818e-01]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.60822491e-16  9.54946524e-02  9.04505348e-01]]


In [5]:
print(ds.hull.equations)

[[-0.         -0.         -1.          0.        ]
 [ 0.         -1.          0.         -0.        ]
 [-1.         -0.         -0.          0.        ]
 [ 0.57735027  0.57735027  0.57735027 -0.57735027]]


In [9]:
points = np.random.rand(10, 3)
ds = ProjectionHandler(points)
print(ds.hull.vertices.shape)

(10,)


In [17]:
import time
query_points = np.random.rand(100000, 3)

In [19]:
start_time = time.time()
ds.project_points(query_points)
end_time = time.time()
print(end_time - start_time)

282.25393438339233


In [18]:
start_time = time.time()
ds.project_points_parallel(query_points)
end_time = time.time()
print(end_time - start_time)

69.37690925598145
